# Generated by Django 5.1.6 on 2025-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
